// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lizebang/learning-proto3/any/any.proto

package any

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Source struct {
	Data                 []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb91169fc377dadc, []int{0}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type Transport struct {
	Data                 *any.Any `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transport) Reset()         { *m = Transport{} }
func (m *Transport) String() string { return proto.CompactTextString(m) }
func (*Transport) ProtoMessage()    {}
func (*Transport) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb91169fc377dadc, []int{1}
}

func (m *Transport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transport.Unmarshal(m, b)
}
func (m *Transport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transport.Marshal(b, m, deterministic)
}
func (m *Transport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transport.Merge(m, src)
}
func (m *Transport) XXX_Size() int {
	return xxx_messageInfo_Transport.Size(m)
}
func (m *Transport) XXX_DiscardUnknown() {
	xxx_messageInfo_Transport.DiscardUnknown(m)
}

var xxx_messageInfo_Transport proto.InternalMessageInfo

func (m *Transport) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type Destination struct {
	Data                 []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Destination) Reset()         { *m = Destination{} }
func (m *Destination) String() string { return proto.CompactTextString(m) }
func (*Destination) ProtoMessage()    {}
func (*Destination) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb91169fc377dadc, []int{2}
}

func (m *Destination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Destination.Unmarshal(m, b)
}
func (m *Destination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Destination.Marshal(b, m, deterministic)
}
func (m *Destination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Destination.Merge(m, src)
}
func (m *Destination) XXX_Size() int {
	return xxx_messageInfo_Destination.Size(m)
}
func (m *Destination) XXX_DiscardUnknown() {
	xxx_messageInfo_Destination.DiscardUnknown(m)
}

var xxx_messageInfo_Destination proto.InternalMessageInfo

func (m *Destination) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Source)(nil), "any.source")
	proto.RegisterType((*Transport)(nil), "any.transport")
	proto.RegisterType((*Destination)(nil), "any.destination")
}

func init() {
	proto.RegisterFile("github.com/lizebang/learning-proto3/any/any.proto", fileDescriptor_cb91169fc377dadc)
}

var fileDescriptor_cb91169fc377dadc = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xc9, 0xac, 0x4a, 0x4d, 0x4a, 0xcc, 0x4b, 0xd7,
	0xcf, 0x49, 0x4d, 0x2c, 0xca, 0xcb, 0xcc, 0x4b, 0xd7, 0x2d, 0x28, 0xca, 0x2f, 0xc9, 0x37, 0xd6,
	0x4f, 0xcc, 0xab, 0x04, 0x61, 0x3d, 0x30, 0x57, 0x88, 0x39, 0x31, 0xaf, 0x52, 0x4a, 0x1f, 0x49,
	0x5f, 0x7a, 0x7e, 0x0e, 0x48, 0x17, 0x58, 0x36, 0xa9, 0x34, 0x4d, 0xbf, 0xa0, 0xa4, 0xb2, 0x20,
	0xb5, 0x18, 0x55, 0x97, 0x92, 0x0c, 0x17, 0x5b, 0x71, 0x7e, 0x69, 0x51, 0x72, 0xaa, 0x90, 0x10,
	0x17, 0x4b, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x98, 0xad, 0x64,
	0xca, 0xc5, 0x59, 0x52, 0x94, 0x98, 0x57, 0x5c, 0x90, 0x5f, 0x54, 0x22, 0xa4, 0x01, 0x57, 0xc0,
	0xa8, 0xc1, 0x6d, 0x24, 0xa2, 0x97, 0x9e, 0x9f, 0x9f, 0x9e, 0x93, 0xaa, 0x07, 0x33, 0x5f, 0xcf,
	0x31, 0xaf, 0x12, 0xaa, 0x4d, 0x91, 0x8b, 0x3b, 0x25, 0xb5, 0xb8, 0x24, 0x33, 0x2f, 0xb1, 0x24,
	0x33, 0x3f, 0x0f, 0x9b, 0xc9, 0x4e, 0x9a, 0x51, 0xea, 0x44, 0x7a, 0x31, 0x89, 0x0d, 0xc2, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xf5, 0x73, 0x6a, 0x14, 0x01, 0x00, 0x00,
}
