// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lizebang/learning-proto3/base/demo/demo.proto

package demo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	new "github.com/lizebang/learning-proto3/base/new"
	_ "github.com/lizebang/learning-proto3/base/old"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ----------------------------
// enum2 reserved
type Enum2 int32

const (
	Enum2_b Enum2 = 0
	Enum2_c Enum2 = 2
)

var Enum2_name = map[int32]string{
	0: "b",
	2: "c",
}

var Enum2_value = map[string]int32{
	"b": 0,
	"c": 2,
}

func (x Enum2) String() string {
	return proto.EnumName(Enum2_name, int32(x))
}

func (Enum2) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{0}
}

type Msg3Enum1 int32

const (
	Msg3_a Msg3Enum1 = 0
	Msg3_b Msg3Enum1 = 1
	Msg3_c Msg3Enum1 = 1
)

var Msg3Enum1_name = map[int32]string{
	0: "a",
	1: "b",
	// Duplicate value: 1: "c",
}

var Msg3Enum1_value = map[string]int32{
	"a": 0,
	"b": 1,
	"c": 1,
}

func (x Msg3Enum1) String() string {
	return proto.EnumName(Msg3Enum1_name, int32(x))
}

func (Msg3Enum1) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{2, 0}
}

// ----------------------------
// msg1 base
type Msg1 struct {
	Field1               int32    `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2               int32    `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3               []int32  `protobuf:"varint,3,rep,packed,name=field3,proto3" json:"field3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg1) Reset()         { *m = Msg1{} }
func (m *Msg1) String() string { return proto.CompactTextString(m) }
func (*Msg1) ProtoMessage()    {}
func (*Msg1) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{0}
}

func (m *Msg1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg1.Unmarshal(m, b)
}
func (m *Msg1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg1.Marshal(b, m, deterministic)
}
func (m *Msg1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg1.Merge(m, src)
}
func (m *Msg1) XXX_Size() int {
	return xxx_messageInfo_Msg1.Size(m)
}
func (m *Msg1) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg1.DiscardUnknown(m)
}

var xxx_messageInfo_Msg1 proto.InternalMessageInfo

func (m *Msg1) GetField1() int32 {
	if m != nil {
		return m.Field1
	}
	return 0
}

func (m *Msg1) GetField2() int32 {
	if m != nil {
		return m.Field2
	}
	return 0
}

func (m *Msg1) GetField3() []int32 {
	if m != nil {
		return m.Field3
	}
	return nil
}

// ----------------------------
// msg2 reserved
type Msg2 struct {
	Field1               int32    `protobuf:"varint,3,opt,name=field1,proto3" json:"field1,omitempty"`
	Field4               int32    `protobuf:"varint,4,opt,name=field4,proto3" json:"field4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg2) Reset()         { *m = Msg2{} }
func (m *Msg2) String() string { return proto.CompactTextString(m) }
func (*Msg2) ProtoMessage()    {}
func (*Msg2) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{1}
}

func (m *Msg2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg2.Unmarshal(m, b)
}
func (m *Msg2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg2.Marshal(b, m, deterministic)
}
func (m *Msg2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg2.Merge(m, src)
}
func (m *Msg2) XXX_Size() int {
	return xxx_messageInfo_Msg2.Size(m)
}
func (m *Msg2) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg2.DiscardUnknown(m)
}

var xxx_messageInfo_Msg2 proto.InternalMessageInfo

func (m *Msg2) GetField1() int32 {
	if m != nil {
		return m.Field1
	}
	return 0
}

func (m *Msg2) GetField4() int32 {
	if m != nil {
		return m.Field4
	}
	return 0
}

// ----------------------------
// msg3 allow_alias
type Msg3 struct {
	Field1               Msg3Enum1 `protobuf:"varint,1,opt,name=field1,proto3,enum=demo.Msg3Enum1" json:"field1,omitempty"`
	Field2               Enum2     `protobuf:"varint,2,opt,name=field2,proto3,enum=demo.Enum2" json:"field2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Msg3) Reset()         { *m = Msg3{} }
func (m *Msg3) String() string { return proto.CompactTextString(m) }
func (*Msg3) ProtoMessage()    {}
func (*Msg3) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{2}
}

func (m *Msg3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg3.Unmarshal(m, b)
}
func (m *Msg3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg3.Marshal(b, m, deterministic)
}
func (m *Msg3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg3.Merge(m, src)
}
func (m *Msg3) XXX_Size() int {
	return xxx_messageInfo_Msg3.Size(m)
}
func (m *Msg3) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg3.DiscardUnknown(m)
}

var xxx_messageInfo_Msg3 proto.InternalMessageInfo

func (m *Msg3) GetField1() Msg3Enum1 {
	if m != nil {
		return m.Field1
	}
	return Msg3_a
}

func (m *Msg3) GetField2() Enum2 {
	if m != nil {
		return m.Field2
	}
	return Enum2_b
}

// ----------------------------
// msg4 msg3.enum1
type Msg4 struct {
	Field1               Msg3Enum1 `protobuf:"varint,1,opt,name=field1,proto3,enum=demo.Msg3Enum1" json:"field1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Msg4) Reset()         { *m = Msg4{} }
func (m *Msg4) String() string { return proto.CompactTextString(m) }
func (*Msg4) ProtoMessage()    {}
func (*Msg4) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{3}
}

func (m *Msg4) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg4.Unmarshal(m, b)
}
func (m *Msg4) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg4.Marshal(b, m, deterministic)
}
func (m *Msg4) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg4.Merge(m, src)
}
func (m *Msg4) XXX_Size() int {
	return xxx_messageInfo_Msg4.Size(m)
}
func (m *Msg4) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg4.DiscardUnknown(m)
}

var xxx_messageInfo_Msg4 proto.InternalMessageInfo

func (m *Msg4) GetField1() Msg3Enum1 {
	if m != nil {
		return m.Field1
	}
	return Msg3_a
}

// ----------------------------
// msg5 msg6
type Msg5 struct {
	Field1               *Msg5Msg6 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Msg5) Reset()         { *m = Msg5{} }
func (m *Msg5) String() string { return proto.CompactTextString(m) }
func (*Msg5) ProtoMessage()    {}
func (*Msg5) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{4}
}

func (m *Msg5) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg5.Unmarshal(m, b)
}
func (m *Msg5) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg5.Marshal(b, m, deterministic)
}
func (m *Msg5) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg5.Merge(m, src)
}
func (m *Msg5) XXX_Size() int {
	return xxx_messageInfo_Msg5.Size(m)
}
func (m *Msg5) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg5.DiscardUnknown(m)
}

var xxx_messageInfo_Msg5 proto.InternalMessageInfo

func (m *Msg5) GetField1() *Msg5Msg6 {
	if m != nil {
		return m.Field1
	}
	return nil
}

type Msg5Msg6 struct {
	Field1               int32    `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg5Msg6) Reset()         { *m = Msg5Msg6{} }
func (m *Msg5Msg6) String() string { return proto.CompactTextString(m) }
func (*Msg5Msg6) ProtoMessage()    {}
func (*Msg5Msg6) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{4, 0}
}

func (m *Msg5Msg6) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg5Msg6.Unmarshal(m, b)
}
func (m *Msg5Msg6) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg5Msg6.Marshal(b, m, deterministic)
}
func (m *Msg5Msg6) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg5Msg6.Merge(m, src)
}
func (m *Msg5Msg6) XXX_Size() int {
	return xxx_messageInfo_Msg5Msg6.Size(m)
}
func (m *Msg5Msg6) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg5Msg6.DiscardUnknown(m)
}

var xxx_messageInfo_Msg5Msg6 proto.InternalMessageInfo

func (m *Msg5Msg6) GetField1() int32 {
	if m != nil {
		return m.Field1
	}
	return 0
}

// ----------------------------
// msg7 msg5.msg6
type Msg7 struct {
	Field1               *Msg5Msg6 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Msg7) Reset()         { *m = Msg7{} }
func (m *Msg7) String() string { return proto.CompactTextString(m) }
func (*Msg7) ProtoMessage()    {}
func (*Msg7) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{5}
}

func (m *Msg7) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg7.Unmarshal(m, b)
}
func (m *Msg7) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg7.Marshal(b, m, deterministic)
}
func (m *Msg7) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg7.Merge(m, src)
}
func (m *Msg7) XXX_Size() int {
	return xxx_messageInfo_Msg7.Size(m)
}
func (m *Msg7) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg7.DiscardUnknown(m)
}

var xxx_messageInfo_Msg7 proto.InternalMessageInfo

func (m *Msg7) GetField1() *Msg5Msg6 {
	if m != nil {
		return m.Field1
	}
	return nil
}

// msg8 old.msg1
type Msg8 struct {
	Field1               *new.Msg1 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Msg8) Reset()         { *m = Msg8{} }
func (m *Msg8) String() string { return proto.CompactTextString(m) }
func (*Msg8) ProtoMessage()    {}
func (*Msg8) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{6}
}

func (m *Msg8) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg8.Unmarshal(m, b)
}
func (m *Msg8) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg8.Marshal(b, m, deterministic)
}
func (m *Msg8) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg8.Merge(m, src)
}
func (m *Msg8) XXX_Size() int {
	return xxx_messageInfo_Msg8.Size(m)
}
func (m *Msg8) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg8.DiscardUnknown(m)
}

var xxx_messageInfo_Msg8 proto.InternalMessageInfo

func (m *Msg8) GetField1() *new.Msg1 {
	if m != nil {
		return m.Field1
	}
	return nil
}

// msg9 old.msg1
type Msg9 struct {
	Field1               *new.Msg1 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Msg9) Reset()         { *m = Msg9{} }
func (m *Msg9) String() string { return proto.CompactTextString(m) }
func (*Msg9) ProtoMessage()    {}
func (*Msg9) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7de0b8ee17f4612, []int{7}
}

func (m *Msg9) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg9.Unmarshal(m, b)
}
func (m *Msg9) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg9.Marshal(b, m, deterministic)
}
func (m *Msg9) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg9.Merge(m, src)
}
func (m *Msg9) XXX_Size() int {
	return xxx_messageInfo_Msg9.Size(m)
}
func (m *Msg9) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg9.DiscardUnknown(m)
}

var xxx_messageInfo_Msg9 proto.InternalMessageInfo

func (m *Msg9) GetField1() *new.Msg1 {
	if m != nil {
		return m.Field1
	}
	return nil
}

func init() {
	proto.RegisterEnum("demo.Enum2", Enum2_name, Enum2_value)
	proto.RegisterEnum("demo.Msg3Enum1", Msg3Enum1_name, Msg3Enum1_value)
	proto.RegisterType((*Msg1)(nil), "demo.msg1")
	proto.RegisterType((*Msg2)(nil), "demo.msg2")
	proto.RegisterType((*Msg3)(nil), "demo.msg3")
	proto.RegisterType((*Msg4)(nil), "demo.msg4")
	proto.RegisterType((*Msg5)(nil), "demo.msg5")
	proto.RegisterType((*Msg5Msg6)(nil), "demo.msg5.msg6")
	proto.RegisterType((*Msg7)(nil), "demo.msg7")
	proto.RegisterType((*Msg8)(nil), "demo.msg8")
	proto.RegisterType((*Msg9)(nil), "demo.msg9")
}

func init() {
	proto.RegisterFile("github.com/lizebang/learning-proto3/base/demo/demo.proto", fileDescriptor_c7de0b8ee17f4612)
}

var fileDescriptor_c7de0b8ee17f4612 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcd, 0x4f, 0xc2, 0x30,
	0x18, 0xc6, 0xe9, 0x36, 0x70, 0x8e, 0x04, 0x9b, 0x1e, 0xcc, 0xc2, 0xc1, 0x60, 0x3d, 0x88, 0x24,
	0xac, 0xd2, 0x01, 0xe2, 0xd5, 0x23, 0x07, 0x4d, 0x3c, 0x1a, 0x2f, 0x1b, 0xd4, 0xb9, 0x64, 0x1f,
	0x86, 0x8f, 0x90, 0x78, 0xda, 0x7f, 0x3e, 0xf3, 0xb6, 0xd2, 0x30, 0xa2, 0xc9, 0x38, 0xb4, 0x85,
	0xa7, 0xef, 0xef, 0x79, 0x9b, 0xf7, 0xc9, 0x9c, 0x59, 0x14, 0x6f, 0x3e, 0xb7, 0xa1, 0xb7, 0xc8,
	0x53, 0x96, 0xc4, 0xdf, 0x22, 0x0c, 0xb2, 0x88, 0x25, 0x22, 0x58, 0x65, 0x71, 0x16, 0x0d, 0xbf,
	0x56, 0xf9, 0x26, 0xf7, 0x59, 0x18, 0xac, 0x05, 0x5b, 0x8a, 0x34, 0x97, 0x9b, 0x27, 0x55, 0x62,
	0xc1, 0xef, 0xee, 0xb4, 0x36, 0x9f, 0x89, 0x1d, 0x2c, 0x45, 0x9f, 0xc0, 0xe5, 0xc9, 0x12, 0x96,
	0xe2, 0xe8, 0xb3, 0x63, 0xa5, 0xeb, 0x68, 0x44, 0x2e, 0x9d, 0xd6, 0x47, 0x2c, 0x92, 0xe5, 0xc8,
	0x45, 0x3d, 0xd4, 0x6f, 0xbe, 0xfe, 0xfe, 0xd3, 0x3a, 0x77, 0x8d, 0x03, 0x9d, 0x6b, 0xdd, 0x77,
	0xcd, 0x9e, 0xa9, 0x75, 0x9f, 0xbe, 0x4b, 0x3f, 0x7e, 0xe0, 0x67, 0xfe, 0xe9, 0x37, 0x76, 0xad,
	0x03, 0x7d, 0x3c, 0xb7, 0x6c, 0x84, 0x8d, 0xb9, 0x65, 0x1b, 0xd8, 0x9c, 0xdb, 0x76, 0x1b, 0x17,
	0x45, 0x51, 0x18, 0xfb, 0x6e, 0xda, 0x7d, 0x27, 0xdd, 0x7d, 0xd2, 0xaf, 0xbc, 0xb6, 0xc3, 0xb1,
	0x27, 0x07, 0x09, 0x77, 0x9e, 0xc8, 0xb6, 0xe9, 0x48, 0xf7, 0xbb, 0xa9, 0xbc, 0xbf, 0xc3, 0xdb,
	0xaa, 0x12, 0x8a, 0xf6, 0xb6, 0x9c, 0xf6, 0x9c, 0xa6, 0xa4, 0x48, 0xd3, 0x41, 0x01, 0x6e, 0xc0,
	0x11, 0x62, 0x04, 0xc7, 0x02, 0xa3, 0xae, 0x81, 0x11, 0xbd, 0x97, 0x8d, 0xc7, 0xf5, 0x1b, 0xd3,
	0x17, 0x49, 0x4c, 0xc8, 0x6d, 0x85, 0x68, 0xf3, 0x0b, 0x4d, 0x4c, 0x60, 0x9b, 0xee, 0x81, 0xee,
	0x95, 0x04, 0xa6, 0xff, 0x25, 0x41, 0x99, 0xbc, 0x7f, 0xa8, 0x6d, 0x48, 0xef, 0x24, 0x30, 0x23,
	0xd7, 0x47, 0xc0, 0xb9, 0x07, 0xf1, 0x43, 0xea, 0x47, 0xa5, 0x8f, 0x35, 0x4a, 0x07, 0x7d, 0x35,
	0x2b, 0xae, 0x86, 0xd4, 0x50, 0x43, 0x32, 0x28, 0xe4, 0x87, 0x28, 0x24, 0x57, 0x96, 0x65, 0x79,
	0x36, 0x40, 0xc1, 0x13, 0x7b, 0x1b, 0x9e, 0xf4, 0x31, 0x84, 0x2d, 0xa5, 0xfc, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xac, 0xc6, 0x48, 0x9e, 0x44, 0x03, 0x00, 0x00,
}
