// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lizebang/learning-proto3/pkg_a/file_a.proto

package pkg_a

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lizebang/learning-proto3/pkg_b"
	pkg_c "github.com/lizebang/learning-proto3/pkg_c"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnumB int32

const (
	EnumB_B EnumB = 0
	EnumB_C EnumB = 2
)

var EnumB_name = map[int32]string{
	0: "B",
	2: "C",
}

var EnumB_value = map[string]int32{
	"B": 0,
	"C": 2,
}

func (x EnumB) String() string {
	return proto.EnumName(EnumB_name, int32(x))
}

func (EnumB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ffe59c252f5a962, []int{0}
}

type MsgCEnumA int32

const (
	MsgC_A MsgCEnumA = 0
	MsgC_B MsgCEnumA = 1
	MsgC_C MsgCEnumA = 1
)

var MsgCEnumA_name = map[int32]string{
	0: "A",
	1: "B",
	// Duplicate value: 1: "C",
}

var MsgCEnumA_value = map[string]int32{
	"A": 0,
	"B": 1,
	"C": 1,
}

func (x MsgCEnumA) String() string {
	return proto.EnumName(MsgCEnumA_name, int32(x))
}

func (MsgCEnumA) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ffe59c252f5a962, []int{2, 0}
}

type MsgA struct {
	FieldA               string   `protobuf:"bytes,1,opt,name=field_a,json=fieldA,proto3" json:"field_a,omitempty"`
	FieldB               int32    `protobuf:"varint,2,opt,name=field_b,json=fieldB,proto3" json:"field_b,omitempty"`
	FieldC               []int32  `protobuf:"varint,3,rep,packed,name=field_c,json=fieldC,proto3" json:"field_c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgA) Reset()         { *m = MsgA{} }
func (m *MsgA) String() string { return proto.CompactTextString(m) }
func (*MsgA) ProtoMessage()    {}
func (*MsgA) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ffe59c252f5a962, []int{0}
}

func (m *MsgA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgA.Unmarshal(m, b)
}
func (m *MsgA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgA.Marshal(b, m, deterministic)
}
func (m *MsgA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgA.Merge(m, src)
}
func (m *MsgA) XXX_Size() int {
	return xxx_messageInfo_MsgA.Size(m)
}
func (m *MsgA) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgA.DiscardUnknown(m)
}

var xxx_messageInfo_MsgA proto.InternalMessageInfo

func (m *MsgA) GetFieldA() string {
	if m != nil {
		return m.FieldA
	}
	return ""
}

func (m *MsgA) GetFieldB() int32 {
	if m != nil {
		return m.FieldB
	}
	return 0
}

func (m *MsgA) GetFieldC() []int32 {
	if m != nil {
		return m.FieldC
	}
	return nil
}

type MsgB struct {
	FieldA               string   `protobuf:"bytes,3,opt,name=field_a,json=fieldA,proto3" json:"field_a,omitempty"`
	FieldD               int32    `protobuf:"varint,4,opt,name=field_d,json=fieldD,proto3" json:"field_d,omitempty"`
	FieldE               []int32  `protobuf:"varint,5,rep,packed,name=field_e,json=fieldE,proto3" json:"field_e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgB) Reset()         { *m = MsgB{} }
func (m *MsgB) String() string { return proto.CompactTextString(m) }
func (*MsgB) ProtoMessage()    {}
func (*MsgB) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ffe59c252f5a962, []int{1}
}

func (m *MsgB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgB.Unmarshal(m, b)
}
func (m *MsgB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgB.Marshal(b, m, deterministic)
}
func (m *MsgB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgB.Merge(m, src)
}
func (m *MsgB) XXX_Size() int {
	return xxx_messageInfo_MsgB.Size(m)
}
func (m *MsgB) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgB.DiscardUnknown(m)
}

var xxx_messageInfo_MsgB proto.InternalMessageInfo

func (m *MsgB) GetFieldA() string {
	if m != nil {
		return m.FieldA
	}
	return ""
}

func (m *MsgB) GetFieldD() int32 {
	if m != nil {
		return m.FieldD
	}
	return 0
}

func (m *MsgB) GetFieldE() []int32 {
	if m != nil {
		return m.FieldE
	}
	return nil
}

type MsgC struct {
	A                    MsgCEnumA `protobuf:"varint,1,opt,name=a,proto3,enum=pkg_a.MsgCEnumA" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MsgC) Reset()         { *m = MsgC{} }
func (m *MsgC) String() string { return proto.CompactTextString(m) }
func (*MsgC) ProtoMessage()    {}
func (*MsgC) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ffe59c252f5a962, []int{2}
}

func (m *MsgC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgC.Unmarshal(m, b)
}
func (m *MsgC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgC.Marshal(b, m, deterministic)
}
func (m *MsgC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgC.Merge(m, src)
}
func (m *MsgC) XXX_Size() int {
	return xxx_messageInfo_MsgC.Size(m)
}
func (m *MsgC) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgC.DiscardUnknown(m)
}

var xxx_messageInfo_MsgC proto.InternalMessageInfo

func (m *MsgC) GetA() MsgCEnumA {
	if m != nil {
		return m.A
	}
	return MsgC_A
}

type MsgD struct {
	FieldA               MsgCEnumA `protobuf:"varint,1,opt,name=field_a,json=fieldA,proto3,enum=pkg_a.MsgCEnumA" json:"field_a,omitempty"`
	FieldB               EnumB     `protobuf:"varint,2,opt,name=field_b,json=fieldB,proto3,enum=pkg_a.EnumB" json:"field_b,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MsgD) Reset()         { *m = MsgD{} }
func (m *MsgD) String() string { return proto.CompactTextString(m) }
func (*MsgD) ProtoMessage()    {}
func (*MsgD) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ffe59c252f5a962, []int{3}
}

func (m *MsgD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgD.Unmarshal(m, b)
}
func (m *MsgD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgD.Marshal(b, m, deterministic)
}
func (m *MsgD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgD.Merge(m, src)
}
func (m *MsgD) XXX_Size() int {
	return xxx_messageInfo_MsgD.Size(m)
}
func (m *MsgD) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgD.DiscardUnknown(m)
}

var xxx_messageInfo_MsgD proto.InternalMessageInfo

func (m *MsgD) GetFieldA() MsgCEnumA {
	if m != nil {
		return m.FieldA
	}
	return MsgC_A
}

func (m *MsgD) GetFieldB() EnumB {
	if m != nil {
		return m.FieldB
	}
	return EnumB_B
}

type MsgE struct {
	FieldA               *MsgEMsgF `protobuf:"bytes,1,opt,name=field_a,json=fieldA,proto3" json:"field_a,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MsgE) Reset()         { *m = MsgE{} }
func (m *MsgE) String() string { return proto.CompactTextString(m) }
func (*MsgE) ProtoMessage()    {}
func (*MsgE) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ffe59c252f5a962, []int{4}
}

func (m *MsgE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgE.Unmarshal(m, b)
}
func (m *MsgE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgE.Marshal(b, m, deterministic)
}
func (m *MsgE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgE.Merge(m, src)
}
func (m *MsgE) XXX_Size() int {
	return xxx_messageInfo_MsgE.Size(m)
}
func (m *MsgE) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgE.DiscardUnknown(m)
}

var xxx_messageInfo_MsgE proto.InternalMessageInfo

func (m *MsgE) GetFieldA() *MsgEMsgF {
	if m != nil {
		return m.FieldA
	}
	return nil
}

type MsgEMsgF struct {
	FieldA               int32    `protobuf:"varint,1,opt,name=field_a,json=fieldA,proto3" json:"field_a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgEMsgF) Reset()         { *m = MsgEMsgF{} }
func (m *MsgEMsgF) String() string { return proto.CompactTextString(m) }
func (*MsgEMsgF) ProtoMessage()    {}
func (*MsgEMsgF) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ffe59c252f5a962, []int{4, 0}
}

func (m *MsgEMsgF) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgEMsgF.Unmarshal(m, b)
}
func (m *MsgEMsgF) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgEMsgF.Marshal(b, m, deterministic)
}
func (m *MsgEMsgF) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEMsgF.Merge(m, src)
}
func (m *MsgEMsgF) XXX_Size() int {
	return xxx_messageInfo_MsgEMsgF.Size(m)
}
func (m *MsgEMsgF) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEMsgF.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEMsgF proto.InternalMessageInfo

func (m *MsgEMsgF) GetFieldA() int32 {
	if m != nil {
		return m.FieldA
	}
	return 0
}

type MsgG struct {
	FieldA               *MsgE       `protobuf:"bytes,1,opt,name=field_a,json=fieldA,proto3" json:"field_a,omitempty"`
	FieldB               *MsgEMsgF   `protobuf:"bytes,2,opt,name=field_b,json=fieldB,proto3" json:"field_b,omitempty"`
	FieldC               *pkg_c.MsgA `protobuf:"bytes,3,opt,name=field_c,json=fieldC,proto3" json:"field_c,omitempty"`
	FieldD               *pkg_c.MsgA `protobuf:"bytes,4,opt,name=field_d,json=fieldD,proto3" json:"field_d,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MsgG) Reset()         { *m = MsgG{} }
func (m *MsgG) String() string { return proto.CompactTextString(m) }
func (*MsgG) ProtoMessage()    {}
func (*MsgG) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ffe59c252f5a962, []int{5}
}

func (m *MsgG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgG.Unmarshal(m, b)
}
func (m *MsgG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgG.Marshal(b, m, deterministic)
}
func (m *MsgG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgG.Merge(m, src)
}
func (m *MsgG) XXX_Size() int {
	return xxx_messageInfo_MsgG.Size(m)
}
func (m *MsgG) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgG.DiscardUnknown(m)
}

var xxx_messageInfo_MsgG proto.InternalMessageInfo

func (m *MsgG) GetFieldA() *MsgE {
	if m != nil {
		return m.FieldA
	}
	return nil
}

func (m *MsgG) GetFieldB() *MsgEMsgF {
	if m != nil {
		return m.FieldB
	}
	return nil
}

func (m *MsgG) GetFieldC() *pkg_c.MsgA {
	if m != nil {
		return m.FieldC
	}
	return nil
}

func (m *MsgG) GetFieldD() *pkg_c.MsgA {
	if m != nil {
		return m.FieldD
	}
	return nil
}

func init() {
	proto.RegisterEnum("pkg_a.EnumB", EnumB_name, EnumB_value)
	proto.RegisterEnum("pkg_a.MsgCEnumA", MsgCEnumA_name, MsgCEnumA_value)
	proto.RegisterType((*MsgA)(nil), "pkg_a.msg_a")
	proto.RegisterType((*MsgB)(nil), "pkg_a.msg_b")
	proto.RegisterType((*MsgC)(nil), "pkg_a.msg_c")
	proto.RegisterType((*MsgD)(nil), "pkg_a.msg_d")
	proto.RegisterType((*MsgE)(nil), "pkg_a.msg_e")
	proto.RegisterType((*MsgEMsgF)(nil), "pkg_a.msg_e.msg_f")
	proto.RegisterType((*MsgG)(nil), "pkg_a.msg_g")
}

func init() {
	proto.RegisterFile("github.com/lizebang/learning-proto3/pkg_a/file_a.proto", fileDescriptor_9ffe59c252f5a962)
}

var fileDescriptor_9ffe59c252f5a962 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6f, 0xa2, 0x40,
	0x14, 0xc6, 0x1d, 0x10, 0x65, 0x71, 0xd7, 0x90, 0xd9, 0xc3, 0x12, 0x4f, 0x38, 0xc9, 0x6e, 0x5c,
	0xdd, 0x85, 0xc4, 0x26, 0xbd, 0xa3, 0xf6, 0x62, 0xd2, 0x0b, 0x87, 0xde, 0x1a, 0x32, 0x83, 0x03,
	0x25, 0x45, 0x34, 0x56, 0x2f, 0x9e, 0xf8, 0x77, 0xfa, 0x57, 0xd2, 0x30, 0xcf, 0x11, 0x30, 0xb6,
	0xf1, 0xe2, 0x38, 0xf3, 0xde, 0xf7, 0x9b, 0x37, 0xdf, 0x87, 0x71, 0x1f, 0x27, 0xfb, 0x97, 0x03,
	0x73, 0xc2, 0xcd, 0xda, 0x4d, 0x93, 0x23, 0x67, 0x34, 0x8b, 0xdd, 0x94, 0xd3, 0x5d, 0x96, 0x64,
	0xf1, 0xff, 0xed, 0x6e, 0xb3, 0xdf, 0xdc, 0xb9, 0xdb, 0xd7, 0x38, 0xa0, 0x6e, 0x94, 0xa4, 0x3c,
	0xa0, 0x8e, 0x38, 0xc3, 0x9a, 0x38, 0x1b, 0xdc, 0x2c, 0x67, 0x20, 0x67, 0x20, 0xbf, 0x5d, 0x17,
	0x82, 0x2e, 0x04, 0x1d, 0xf1, 0x0d, 0x6d, 0xfd, 0x16, 0x07, 0x14, 0xff, 0x32, 0xba, 0x51, 0xc2,
	0xd3, 0x55, 0x40, 0x2d, 0x64, 0xa3, 0xd1, 0x37, 0xbf, 0x23, 0xb6, 0x5e, 0x55, 0x60, 0x96, 0x62,
	0xa3, 0x91, 0x76, 0x2a, 0xcc, 0xaa, 0x42, 0x68, 0xa9, 0xb6, 0x7a, 0x2e, 0xcc, 0xc9, 0x11, 0x98,
	0xac, 0xce, 0x54, 0xaf, 0x33, 0x57, 0x56, 0xbb, 0xc6, 0x5c, 0x54, 0x05, 0x6e, 0x69, 0x35, 0xe6,
	0xc3, 0xb2, 0xad, 0x23, 0x53, 0x59, 0xb6, 0x75, 0xc5, 0x54, 0x97, 0xba, 0xde, 0x33, 0xf3, 0x3c,
	0xcf, 0x15, 0x5f, 0x4e, 0x26, 0xff, 0x84, 0xe4, 0x11, 0xee, 0x0e, 0xf1, 0xd0, 0x40, 0xf0, 0x92,
	0xfe, 0xf4, 0xa7, 0x23, 0xbc, 0x75, 0x44, 0xc1, 0xe1, 0xd9, 0x61, 0x1d, 0x50, 0x1f, 0x51, 0x32,
	0x34, 0x3a, 0xb0, 0xc1, 0x9a, 0x81, 0x3c, 0xb3, 0x55, 0x2e, 0x33, 0x13, 0x95, 0xcb, 0xdc, 0x44,
	0x03, 0xc5, 0x44, 0xe4, 0x19, 0x70, 0x2b, 0xfc, 0xaf, 0x69, 0xcf, 0x27, 0x50, 0xf9, 0xbe, 0x3f,
	0x4d, 0xcf, 0xfa, 0xd3, 0x1f, 0xa7, 0x6e, 0xd1, 0xc7, 0xa4, 0x85, 0xe4, 0x09, 0xf0, 0x1c, 0x4f,
	0x9a, 0xf8, 0xde, 0x14, 0xd7, 0xf0, 0x5c, 0xfc, 0x46, 0x92, 0x3e, 0xb0, 0x41, 0x15, 0x5d, 0x66,
	0x26, 0xdd, 0xf2, 0xc8, 0x3b, 0x82, 0x96, 0x18, 0xff, 0xbe, 0x04, 0x7f, 0xaf, 0x83, 0xcf, 0x03,
	0x4f, 0x9a, 0x03, 0x7f, 0x75, 0xff, 0xac, 0x62, 0x86, 0x22, 0x56, 0xc9, 0x64, 0xa2, 0x4d, 0x9a,
	0x30, 0xaf, 0xda, 0x20, 0xe4, 0xeb, 0x6d, 0x8b, 0xf1, 0xdf, 0x53, 0x0a, 0x0c, 0xec, 0x6f, 0x81,
	0xfd, 0x0a, 0x29, 0x13, 0x47, 0xa4, 0xcc, 0xba, 0x28, 0x8a, 0xa2, 0x3b, 0x46, 0x1e, 0xeb, 0xc0,
	0x77, 0xfc, 0x11, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xf4, 0x42, 0xe9, 0x64, 0x03, 0x00, 0x00,
}
