// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lizebang/learning-proto3/pkg_c/file_c.proto

package pkg_b

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// from pkg_b/file_b.proto
type MsgA struct {
	FieldA               int32    `protobuf:"varint,1,opt,name=field_a,json=fieldA,proto3" json:"field_a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgA) Reset()         { *m = MsgA{} }
func (m *MsgA) String() string { return proto.CompactTextString(m) }
func (*MsgA) ProtoMessage()    {}
func (*MsgA) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d412dd4ef9febf9, []int{0}
}

func (m *MsgA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgA.Unmarshal(m, b)
}
func (m *MsgA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgA.Marshal(b, m, deterministic)
}
func (m *MsgA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgA.Merge(m, src)
}
func (m *MsgA) XXX_Size() int {
	return xxx_messageInfo_MsgA.Size(m)
}
func (m *MsgA) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgA.DiscardUnknown(m)
}

var xxx_messageInfo_MsgA proto.InternalMessageInfo

func (m *MsgA) GetFieldA() int32 {
	if m != nil {
		return m.FieldA
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgA)(nil), "pkg_b.msg_a")
}

func init() {
	proto.RegisterFile("github.com/lizebang/learning-proto3/pkg_c/file_c.proto", fileDescriptor_5d412dd4ef9febf9)
}

var fileDescriptor_5d412dd4ef9febf9 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4b, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xc9, 0xac, 0x4a, 0x4d, 0x4a, 0xcc, 0x4b, 0xd7,
	0xcf, 0x49, 0x4d, 0x2c, 0xca, 0xcb, 0xcc, 0x4b, 0xd7, 0x2d, 0x28, 0xca, 0x2f, 0xc9, 0x37, 0xd6,
	0x2f, 0xc8, 0x4e, 0x8f, 0x4f, 0xd6, 0x4f, 0xcb, 0xcc, 0x49, 0x8d, 0x4f, 0xd6, 0x03, 0x8b, 0x09,
	0xb1, 0x82, 0xc4, 0x92, 0x94, 0x14, 0xb8, 0x58, 0x73, 0x8b, 0xd3, 0xe3, 0x13, 0x85, 0xc4, 0xb9,
	0xd8, 0xd3, 0x32, 0x53, 0x73, 0x52, 0xe2, 0x13, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xd8,
	0xc0, 0x5c, 0xc7, 0x24, 0x36, 0x88, 0x19, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x68, 0x65,
	0x5b, 0x69, 0x00, 0x00, 0x00,
}
