// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lizebang/learning-proto3/base/new/new.proto

package new

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// msg1 from base/old/old.proto
type Msg1 struct {
	Field1               int32    `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg1) Reset()         { *m = Msg1{} }
func (m *Msg1) String() string { return proto.CompactTextString(m) }
func (*Msg1) ProtoMessage()    {}
func (*Msg1) Descriptor() ([]byte, []int) {
	return fileDescriptor_47b23beaaed0287b, []int{0}
}

func (m *Msg1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg1.Unmarshal(m, b)
}
func (m *Msg1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg1.Marshal(b, m, deterministic)
}
func (m *Msg1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg1.Merge(m, src)
}
func (m *Msg1) XXX_Size() int {
	return xxx_messageInfo_Msg1.Size(m)
}
func (m *Msg1) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg1.DiscardUnknown(m)
}

var xxx_messageInfo_Msg1 proto.InternalMessageInfo

func (m *Msg1) GetField1() int32 {
	if m != nil {
		return m.Field1
	}
	return 0
}

func init() {
	proto.RegisterType((*Msg1)(nil), "old.msg1")
}

func init() {
	proto.RegisterFile("github.com/lizebang/learning-proto3/base/new/new.proto", fileDescriptor_47b23beaaed0287b)
}

var fileDescriptor_47b23beaaed0287b = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4b, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xc9, 0xac, 0x4a, 0x4d, 0x4a, 0xcc, 0x4b, 0xd7,
	0xcf, 0x49, 0x4d, 0x2c, 0xca, 0xcb, 0xcc, 0x4b, 0xd7, 0x2d, 0x28, 0xca, 0x2f, 0xc9, 0x37, 0xd6,
	0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0xcf, 0x4b, 0x2d, 0x07, 0x61, 0x3d, 0xb0, 0x98, 0x10, 0x73, 0x7e,
	0x4e, 0x8a, 0x92, 0x1c, 0x17, 0x4b, 0x6e, 0x71, 0xba, 0xa1, 0x90, 0x18, 0x17, 0x5b, 0x5a, 0x66,
	0x6a, 0x4e, 0x8a, 0xa1, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x94, 0xe7, 0xa4, 0x17, 0xa5,
	0x43, 0x8a, 0xf1, 0x49, 0x6c, 0x10, 0x01, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x99, 0xd7,
	0x50, 0x95, 0x00, 0x00, 0x00,
}
